ALTER TABLE chat_session
  MODIFY COLUMN id VARCHAR(36) NOT NULL;

ALTER TABLE chat_message
  MODIFY COLUMN id VARCHAR(36) NOT NULL,
  MODIFY COLUMN session_id VARCHAR(36) NOT NULL;

ALTER TABLE chat_run
  MODIFY COLUMN id VARCHAR(36) NOT NULL,
  MODIFY COLUMN session_id VARCHAR(36) NOT NULL;
